## 1. 워드클라우드 단어 count 파일, 감성분석 최고 기여 단어 파일 병합, 약간의 전처리

In [1]:
import pandas as pd

df1 = pd.read_excel('금산인삼축제 뉴스제목 워드클라우드.xlsx')
df2 = pd.read_excel('금산인삼축제 감성분석 최고 기여 단어.xlsx')

# 'text' 열과 'top_words' 열을 기준으로 병합
merged_df = pd.merge(df1, df2, left_on='text', right_on='top_word', how='inner')

# 중복된 행 제거
merged_df.drop_duplicates(inplace=True)

# 'text' 칼럼 삭제
merged_df.drop(columns=['text'], inplace=True)

# 칼럼 순서 조정
merged_df = merged_df.reindex(columns=['top_word', 'count', 'label', 'confidence'])

# 결과를 엑셀 파일로 저장
merged_df.to_excel('금산인삼축제 워드클라우드, 감성분석 병합.xlsx', index=False)

In [2]:
merged_df

,top_word,count,label,confidence
0,바가지,8,neutral,"{'negative': 0.4768505, 'positive': 0.9262471,..."
1,지역,24,neutral,"{'negative': 0.03973292, 'positive': 0.0508773..."
2,관광,20,neutral,"{'negative': 0.12969592, 'positive': 0.2788364..."
3,공사,6,neutral,"{'negative': 0.23741001, 'positive': 24.161798..."
4,백종원,27,neutral,"{'negative': 0.052319366, 'positive': 0.152893..."
...,...,...,...,...
132,정리,1,neutral,"{'negative': 0.041334197, 'positive': 0.025046..."
133,붐업,1,neutral,"{'negative': 0.11652939, 'positive': 3.8259788..."
134,직원,1,neutral,"{'negative': 0.03224166, 'positive': 0.0307524..."
135,수출,1,neutral,"{'negative': 0.06320516, 'positive': 0.1220618..."
136,대형,1,neutral,"{'negative': 0.5416572, 'positive': 0.11676115..."