In [5]:
import json
import pandas as pd

df = pd.read_excel('금산인삼축제 워드클라우드, 감성분석 병합.xlsx')
df

,top_word,count,label,confidence
0,가로수,1,neutral,"{'negative': 0.01611653, 'positive': 0.0266103..."
1,가을,10,neutral,"{'negative': 0.101730466, 'positive': 22.61934..."
2,간다,1,neutral,"{'negative': 4.541487, 'positive': 0.8141132, ..."
3,감초,1,neutral,"{'negative': 0.04518094, 'positive': 0.707581,..."
4,강남,1,neutral,"{'negative': 0.041334197, 'positive': 0.025046..."
...,...,...,...,...
111,하나,1,neutral,"{'negative': 2.0577593, 'positive': 0.47161692..."
112,한글날,1,positive,"{'negative': 0.02052887, 'positive': 99.950584..."
113,한일축제한마당,1,neutral,"{'negative': 0.049509645, 'positive': 0.023012..."
114,해외,2,neutral,"{'negative': 0.08261127, 'positive': 1.5229937..."
115,황금,1,neutral,"{'negative': 0.018520147, 'positive': 0.062049..."

In [6]:
# 문자열을 딕셔너리로 변환하는 함수
def str_to_dict(conf_str):
    # 작은 따옴표를 큰 따옴표로 변경 (json.loads가 제대로 작동하게 하기 위해)
    conf_str = conf_str.replace("'", '"')
    return json.loads(conf_str)

# confidence 칼럼의 문자열을 딕셔너리로 변환
df['confidence'] = df['confidence'].apply(str_to_dict)

print(df)

    top_word  count     label  \
0        가로수      1   neutral
1         가을     10   neutral
2         간다      1   neutral
3         감초      1   neutral
4         강남      1   neutral
..       ...    ...       ...
111       하나      1   neutral
112      한글날      1  positive
113  한일축제한마당      1   neutral
114       해외      2   neutral
115       황금      1   neutral

                                            confidence
0    {'negative': 0.01611653, 'positive': 0.0266103...
1    {'negative': 0.101730466, 'positive': 22.61934...
2    {'negative': 4.541487, 'positive': 0.8141132, ...
3    {'negative': 0.04518094, 'positive': 0.707581,...
4    {'negative': 0.041334197, 'positive': 0.025046...
..                                                 ...
111  {'negative': 2.0577593, 'positive': 0.47161692...
112  {'negative': 0.02052887, 'positive': 99.950584...
113  {'negative': 0.049509645, 'positive': 0.023012...
114  {'negative': 0.08261127, 'positive': 1.5229937...
115  {'negative': 0.018520147, 'positive': 0.062049...

[116 rows x 4 columns]

In [7]:
# 딕셔너리를 별도의 칼럼으로 분리
confidence_df = df['confidence'].apply(pd.Series)

# 반올림하여 소수점 첫번째 자리까지 표시
confidence_df = confidence_df.round(2)

# 원본 데이터프레임에 새로운 칼럼 추가
df = pd.concat([df.drop(columns=['confidence']), confidence_df], axis=1)

print(df)

    top_word  count     label  negative  positive  neutral
0        가로수      1   neutral      0.02      0.03    99.96
1         가을     10   neutral      0.10     22.62    77.28
2         간다      1   neutral      4.54      0.81    94.64
3         감초      1   neutral      0.05      0.71    99.25
4         강남      1   neutral      0.04      0.03    99.93
..       ...    ...       ...       ...       ...      ...
111       하나      1   neutral      2.06      0.47    97.47
112      한글날      1  positive      0.02     99.95     0.03
113  한일축제한마당      1   neutral      0.05      0.02    99.93
114       해외      2   neutral      0.08      1.52    98.39
115       황금      1   neutral      0.02      0.06    99.92

[116 rows x 6 columns]

In [8]:
# 결과를 엑셀 파일로 저장
df.to_excel('금산인삼축제 감성분석 최종.xlsx', index=False)