In [1]:
import json
import pandas as pd

df = pd.read_excel('금산천벚꽃축제 워드클라우드, 감성분석 병합.xlsx')
df

,top_word,count,label,confidence
0,축제,81,neutral,"{'negative': 0.014002981, 'positive': 0.067019..."
1,벚꽃,76,neutral,"{'negative': 0.034607727, 'positive': 0.047634..."
2,개화,8,neutral,"{'negative': 0.06473924, 'positive': 0.1451256..."
3,개최,7,neutral,"{'negative': 0.023951015, 'positive': 0.025220..."
4,금산군,6,negative,"{'negative': 99.81618, 'positive': 0.008233529..."
...,...,...,...,...
78,석촌호수,1,neutral,"{'negative': 0.033925086, 'positive': 0.033209..."
79,추천,1,positive,"{'negative': 0.04697905, 'positive': 98.35619,..."
80,경남,1,neutral,"{'negative': 0.059205964, 'positive': 0.991595..."
81,사색,1,neutral,"{'negative': 0.05601185, 'positive': 0.4311116..."
82,일정,1,neutral,"{'negative': 0.09574045, 'positive': 0.0446443..."

In [2]:
# 문자열을 딕셔너리로 변환하는 함수
def str_to_dict(conf_str):
    # 작은 따옴표를 큰 따옴표로 변경 (json.loads가 제대로 작동하게 하기 위해)
    conf_str = conf_str.replace("'", '"')
    return json.loads(conf_str)

# confidence 칼럼의 문자열을 딕셔너리로 변환
df['confidence'] = df['confidence'].apply(str_to_dict)

print(df)

   top_word  count     label  \
0        축제     81   neutral
1        벚꽃     76   neutral
2        개화      8   neutral
3        개최      7   neutral
4       금산군      6  negative
..      ...    ...       ...
78     석촌호수      1   neutral
79       추천      1  positive
80       경남      1   neutral
81       사색      1   neutral
82       일정      1   neutral

                                           confidence
0   {'negative': 0.014002981, 'positive': 0.067019...
1   {'negative': 0.034607727, 'positive': 0.047634...
2   {'negative': 0.06473924, 'positive': 0.1451256...
3   {'negative': 0.023951015, 'positive': 0.025220...
4   {'negative': 99.81618, 'positive': 0.008233529...
..                                                ...
78  {'negative': 0.033925086, 'positive': 0.033209...
79  {'negative': 0.04697905, 'positive': 98.35619,...
80  {'negative': 0.059205964, 'positive': 0.991595...
81  {'negative': 0.05601185, 'positive': 0.4311116...
82  {'negative': 0.09574045, 'positive': 0.0446443...

[83 rows x 4 columns]

In [3]:
# 딕셔너리를 별도의 칼럼으로 분리
confidence_df = df['confidence'].apply(pd.Series)

# 반올림하여 소수점 첫번째 자리까지 표시
confidence_df = confidence_df.round(2)

# 원본 데이터프레임에 새로운 칼럼 추가
df = pd.concat([df.drop(columns=['confidence']), confidence_df], axis=1)

print(df)

   top_word  count     label  negative  positive  neutral
0        축제     81   neutral      0.01      0.07    99.92
1        벚꽃     76   neutral      0.03      0.05    99.92
2        개화      8   neutral      0.06      0.15    99.79
3        개최      7   neutral      0.02      0.03    99.95
4       금산군      6  negative     99.82      0.01     0.18
..      ...    ...       ...       ...       ...      ...
78     석촌호수      1   neutral      0.03      0.03    99.93
79       추천      1  positive      0.05     98.36     1.60
80       경남      1   neutral      0.06      0.99    98.95
81       사색      1   neutral      0.06      0.43    99.51
82       일정      1   neutral      0.10      0.04    99.86

[83 rows x 6 columns]

In [4]:
# 결과를 엑셀 파일로 저장
df.to_excel('금산천벚꽃축제 감성분석 최종.xlsx', index=False)